database_prod: 
  dbname: db_mysql
  dbtable: music
  dburl: jeff.prod.com
database_test: 
  dbname: db_mysql-test
  dbtable: music
  dburl: jeff.test.com
food:
  drink: beer
  eat: Peanut Butter and Jelly sandwich
pods: 
  image: yanivomc/spring-music
  replica: 1
  tag: latest
services:
  port: 80
  targetport: 8080
  name: http
  type: LoadBalancer
  protocol: TCP
app:
  port: 8080
  name: http
  protocol: TCP
