apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "spring.labels" . | nindent 4}}
data:
  dbname: {{ .Values.database_prod.dbname }}
  dbtable: {{ .Values.database_prod.dbtable }}
  dburl: {{ .Values.database_prod.dburl }}
  drink: {{ .Values.food.drink | upper }}
  eat: {{ .Values.food.eat | upper | trunc 13 | quote }}
