apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Chart.Name}}-{{.Chart.Version}}"  
  labels:
  {{- include "spring.labels" . |nindent 4}}
spec:
  replicas: {{ .Values.pods.replica }}
  selector:
    matchLabels:
      {{- include "spring.labels" . |nindent 6}}
  template:
    metadata:
      labels:
        {{- include "spring.labels" . |nindent 8}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.pods.image }}:{{.Values.pods.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{.Values.app.name}}
              containerPort: {{.Values.app.port}}
              protocol: {{.Values.app.protocol}}

