apiVersion: v1
kind: Service
metadata:
  name: spring-music
  {{- include "spring.labels" . | nindent 2}}
spec:
  type: LoadBalancer
  ports:
    - name: {{.Values.services.name}}
      protocol: {{.Values.services.protocol}}
      port: {{.Values.services.port}}
      targetPort: {{.Values.services.targetport}}

